# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#

default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  variables:
    sql_mode: TRADITIONAL
development:
  <<: *default
  database: 'glm_backend_db_test'
test:
  <<: *default
  database: 'glm_backend_db_test'
production:
  <<: *default
  database: 'mosque_prayer_slots'
